language: php
php:
    - 7.2
install:
    - composer global require 'hirak/prestissimo:^0.3' --no-suggest --no-interaction --prefer-dist --no-progress
    - composer install --no-suggest --no-interaction --no-scripts
script: make test
directories:
    - $HOME/.composer/cache/files
