doctrine:
    dbal:
        driver: pdo_sqlite
        memory: true
    orm:
        entity_managers:
            default:
                auto_mapping: true

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    RestApiBundle\:
        resource: '../../../src/{Command}/*'
