doctrine:
    dbal:
        driver: pdo_sqlite
        memory: true
    orm:
        entity_managers:
            default:
                auto_mapping: true

framework:
    translator: ~
    validation: ~

parameters:
    kernel.secret: docs-secret

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    RestApiBundle\:
        resource: '../../../src/{Command}/*'
