services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true
    _instanceof:
        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 25 }

        RestApiBundle\Services\Mapper\Transformer\TransformerInterface:
            tags: [!php/const RestApiBundle\DependencyInjection\CompilerPass\RequestModelTransformerCompilerPass::TAG]

    RestApiBundle\:
        resource: '../../../src/{EventSubscriber,Services,Command}/*'
