services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $parameterBag: '@=service("kernel").getContainer().getParameterBag()' # symfony 4 magic

    _instanceof:
        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 25 }

    RestApiBundle\Manager\:
        resource: '../../../src/Manager/*'
        public: true

    RestApiBundle\EventSubscriber\:
        resource: '../../../src/EventSubscriber/*'

    RestApiBundle\HelperService\:
        resource: '../../../src/HelperService/*'
